# Generated by Django 3.2.7 on 2022-02-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contacts_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='age',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='email',
        ),
    ]
